 233 *sámegielalaš
 146 *vejolaš
 127 *daid
  98 *ee
  82 *searvadahttindepartemeanta
  76 *Romssa
  73 *ulbmil
  71 *ovttasráđiid
  70 *oarjilsámegillii
  66 *oarjilsámi
  66 *oarjilsámegiela
  50 *sierranas
  49 *báikkálaš
  46 *oahppiid
  44 *dain
  43 *oidnosii
  42 *nr
  42 *fágalaš
  40 *oarjilsámegielas
  36 *guđege
  36 *eanaš
  34 *álggahit
  33 *oktasaš
  33 *našunála
  32 *Sámegielalaš
  30 *omd
  30 *fuolahusdepartemeanta
  30 *bálvalusaid
  28 *stáhtalaš
  28 *riikkalaš
  28 *nammasaš
  26 *Ulbmil
  25 *álggahan
  25 *oaččuhit
  24 *viehka
  24 *sensurerejuvvo
  24 *gč
  24 *guovdilis
  23 *árbevirolaš
  22 *oahppiide
  22 *oahpaheaddjiid
  22 *bajimuš
  21 *geatnegahtton
  20 *oarjilsámegielalaš
  20 *jo
  20 *heivehuvvon
  20 *geavaheaddjiide
  20 *ealáskahttit
  19 *dohkálaš
  19 *b
  18 *čuovvoleami
  18 *vástesaš
  18 *ovddimusat
  18 *nubbegiellan
  18 *jogo
  18 *guovttegielalašvuođa
  18 *deattuha
  18 *báikkálaččat
  18 *Snoasa
  17 *čujuha
  17 *og
  17 *gullevaš
  16 *vuorbáduvvot
  16 *oarjilsámegiella
  16 *joatkevaš
  16 *guvllolaš
  16 *gozihit
  16 *geavaheaddjiid
  16 *daidda
  16 *bissovaš
  14 *vuosttamuš
  14 *skoviid
  14 *otnáš
  14 *oppalaš
  14 *oppa
  14 *kárten
  14 *juridihkalaš
  14 *joregiin
  14 *jahkásaš
  14 *giellafágalaš
  14 *dađistaga
  14 *bálvalusat
  14 *bastá
  14 *Zealánddas
  14 *Stbïevnesisnie
  14 *Divttasvuona
  14 *Aotearoas/Orre
  13 *muddui
  13 *heivehit
  13 *dáhpáhusain
  13 *duogáš
  12 *čearddalaš
  12 *álggahuvvot
  12 *vásáhusat
  12 *statistihkka
  12 *siskkilda
  12 *servicesenter
  12 *registariin
  12 *pedagogalaš
  12 *ortnegat
  12 *oktagaslaš
  12 *márkosámi
  12 *láidestusat
  12 *kymrigiela
  12 *joregat
  12 *jna
  12 *guovttegielalaš
  12 *guhkesáigásaš
  12 *geatnegasvuođaid
  12 *elektruvnnalaš
  12 *ealáskahttin
  12 *deattuhit
  12 *bihtánsámi
  12 *bihtánsámegiela
  12 *Kártet
  12 *Justiisa-
  12 *Eanaš
  12 *Departementenes
  12 *Bodeaju
  11 *álggahuvvui
  11 *álggahuvvon
  11 *váldoulbmil
  11 *vuoruhit
  11 *systemáhtalaš
  11 *studerenráhkkanahtti
  11 *skuvlarelevánta
  11 *ortnega
  11 *Jo2
  10 *www*nav*no
  10 *válddahallá
  10 *váillálaš
  10 *vuollásaš
  10 *ulbmiliid
  10 *suomagiela
  10 *rámaid
  10 *politihkalaš
  10 *ortnegiid
  10 *norgalaš
  10 *nanusmuvvá
  10 *milj
  10 *láhkai
  10 *kártet
  10 *julevsámegielalaš
  10 *joregiid
  10 *johtui
  10 *jahkásaččat
  10 *iragiela
  10 *girkolaš
  10 *gielddalaš
  10 *geográfalaš
  10 *geatnegasvuohta
  10 *for
  10 *fidnofágalaš
  10 *etáhta
  10 *dárogielalaš
  10 *dohkálaččat
  10 *divaštallat
  10 *digitála
  10 *bođolaš
  10 *Walesas
  10 *Te
  10 *Reo
  10 *Kōhanga
  10 *Jo3
  10 *Dain
  10 *Daid
   9 *vejolaččat
   9 *searvat
   9 *máŋggakultuvrralaš
   9 *integrerejuvvon
   9 *heivehuvvot
   9 *gustovaš
   9 *duššefal
   9 *deattuhuvvo
   8 *áŋgiruššan
   8 *áŋgiruššama
   8 *vuođđuduvvui
   8 *vuođđuduvvo
   8 *virgádit
   8 *ulbmilat
   8 *syntehtalaš
   8 *spesialistalaš
   8 *rámmaplánalávdegoddi
   8 *rekruhttema
   8 *registariidda
   8 *reflekteret
   8 *ovttaárvosaš
   8 *oahpaheaddjiide
   8 *neahttabáiki
   8 *máŋggabealat
   8 *meänkieli
   8 *maŋemus
   8 *maorigiela
   8 *kártema
   8 *kymrigiella
   8 *kritihkalaš
   8 *ihčodaga
   8 *gáiddosoahpahusa
   8 *gáibádusaid
   8 *gulaskuddamii
   8 *geatnegasvuođa
   8 *geatnegasat
   8 *fuolaha
   8 *eurohpalaš
   8 *eaŋgalasgiella
   8 *dárkileappot
   8 *doibmet
   8 *dohkkehuvvon
   8 *doaimmahusain
   8 *doaimmahit
   8 *dagahit
   8 *bálvalusaide
   8 *buohkanassii
   8 *bohtosat
   8 *boahtteáigásaš
   8 *badjelasas
   8 *almmuhusaid
   8 *Stbïevnesen
   8 *Ortnet
   8 *Oarjilsámi
   8 *Oahppiin
   8 *Konfliktaráđiid
   8 *Joatkevaččat
   7 *čujuhuvvo
   7 *ámmátlaš
   7 *álggahuvvojit
   7 *vásáhusaid
   7 *vuođđudan
   7 *profešuvdnii
   7 *jeavddalaččat
   7 *galbet
   7 *doaibmá
   7 *diđolaš
   7 *buhttet
   7 *aktiivvalaš
   7 *III
   6 *čujuhan
   6 *čovdosiid
   6 *áššáigullevaš
   6 *áŋgiruššat
   6 *álggaha
   6 *álgaga
   6 *vuođđudit
   6 *vuoruhuvvon
   6 *veršuvnna
   6 *vejolažžan
   6 *ulbmáda
   6 *teknologiija
   6 *tearpmat
   6 *sturron
   6 *stuorrudit
   6 *studerengelbbolašvuhtii
   6 *strategalaš
   6 *stipeanddaid
   6 *statistihkas
   6 *statistihkaid
   6 *statistihka
   6 *sosiálasuorggis
   6 *sosiálafágalaš
   6 *sorjá
   6 *skotlándda
   6 *siskkildit
   6 *searaid
   6 *samiske
   6 *samIT
   6 *rápmaplána
   6 *rutiinnaid
   6 *ruhtadit
   6 *ruhtadeapmi
   6 *ruhtada
   6 *rekruhttet
   6 *rekruhttenvuođu
   6 *rekruhtten
   6 *psyhkalaš
   6 *parlamentáralaš
   6 *ovdaskuvlaoahpaheaddjiid
   6 *ortnet
   6 *olámuttus
   6 *oktilaččat
   6 *oahppiin
   6 *nuortalašgiela
   6 *nanusmahttit
   6 *mánáidáitara
   6 *maŋás
   6 *láidestusgihppaga
   6 *kriminálafuolas
   6 *kriminálafuola
   6 *kandidáhtaide
   6 *julev-
   6 *iragiella
   6 *i
   6 *hárvvibut
   6 *gárvánit
   6 *gáibádusat
   6 *gullevašvuođa
   6 *giellapolitihkalaš
   6 *geavatlaš
   6 *geallagiella
   6 *gaskaboddasaš
   6 *galbbat
   6 *fágaidrasttideaddji
   6 *fylkkagielddalaš
   6 *fierpmádat
   6 *etáhtat
   6 *eatnigielalaš
   6 *ealáskahttimis
   6 *ealáskahttimii
   6 *ealáhusaid
   6 *dávvisámegillii
   6 *dávjjimusat
   6 *dovddahit
   6 *doaimmahusat
   6 *diđolašvuođa
   6 *diđolaččat
   6 *divššohasaid
   6 *bálvalusfálaldagaid
   6 *blankeahtaid
   6 *bissovašvuohta
   6 *bieđgguid
   6 *badjelii
   6 *aspiránttaid
   6 *Várdobáiki
   6 *Váldosivva
   6 *UTF-8
   6 *UNESCO
   6 *Statistihkalaš
   6 *Snåsningen
   6 *Oaččuhit
   6 *Nuortalaš
   6 *NRK
   6 *Kriminálafuolla
   6 *Kriminálafuola
   6 *Justiisadepartemeanta
   6 *Helgelándda
   6 *Gč
   6 *Gihppagat
   6 *Etáhta
   6 *Divttasvuonas
   6 *Dađistaga
   6 *Bihtánsámi
   6 *Bargoja
   5 *čujuhit
   5 *árbevirolaččat
   5 *álggahuvvo
   5 *viidáseappot
   5 *sajádaga
   5 *rápmaeavttuid
   5 *paragráfas
   5 *oč
   5 *ovttamielalaš
   5 *ovdalaš
   5 *mielddusteavsttas
   5 *hálidan
   5 *gávnnahit
   5 *goappaš
   5 *geavada
   5 *doaibmi
   5 *demokráhtalaš
   5 *bistá
   5 *ainovdánahttit
   5 *Vásáhusat
   5 *Jo1
   5 *A
   4 musihken/*juigosiid
   4 @\^*Daid
   4 *šláddjiivuohta
   4 *čuovvolit
   4 *čuovvoleapmái
   4 *čuovvoleapmi
   4 *čuovvoleamis
   4 *čuovvolan
   4 *čovdosa
   4 *ámmátetihkalaš
   4 *álkkásmahttit
   4 *álggahii
   4 *áigeguovdilis
   4 *Árbevirolaš
   4 *Álggaheapmi
   4 *válmmaštit
   4 *válmmašta
   4 *válljodat
   4 *váddát
   4 *vuođđudeapmái
   4 *vuođđudeapmi
   4 *vuođđuda
   4 *vuostáiváldit
   4 *vuostáiváldet
   4 *vuoruhuvvojit
   4 *viidáset
   4 *viidáneami
   4 *unnu
   4 *unnitlohkosaš
   4 *unnitlohkogielalaš
   4 *ulbmálaččat
   4 *ulbmiliin
   4 *til
   4 *testameantta
   4 *tearpmaid
   4 *sámidáru
   4 *sámegielgelbbolašvuođa
   4 *sámegielalaččat
   4 *suoma-*ugralaš
   4 *stipeandda
   4 *sosiálabálvalusaid
   4 *skovit
   4 *sivva
   4 *siva
   4 *sisttisdoallá
   4 *sihkkarastá
   4 *sihkkarastojuvvot
   4 *sihkkarastet
   4 *servet
   4 *selvána
   4 *searvan
   4 *searvadahttindepartemeanttas
   4 *searvadahttindepartemeanttain
   4 *samisk
   4 *rápmaplánas
   4 *rápmaeavttut
   4 *rámmaplánaid
   4 *rájáid
   4 *rájá
   4 *ruoŧŧilaš
   4 *registarastojuvvot
   4 *regionála
   4 *referánsateavsttat
   4 *rasttideaddji
   4 *radios
   4 *publikasjonsbestilling@*dss*dep*no
   4 *polynesalaš
   4 *ovttastallangiella
   4 *ovttastallan-
   4 *ovttagielalaš
   4 *ovddimussii
   4 *ovddasmanni
   4 *olut
   4 *ollugat
   4 *olgoriikkalaš
   4 *oktagasat
   4 *oinnolaš
   4 *oaččuhivččii
   4 *oasálaččat
   4 *oainnusin
   4 *nuortalašgiela/*golttágiela
   4 *nugohčoduvvon
   4 *nubbingiellanfágas
   4 *njuovžilat
   4 *njulgestaga
   4 *neahttabáikkiin
   4 *neahttabáikkiide
   4 *neahttabáikki
   4 *neahtas
   4 *nanusmahttimii
   4 *máin
   4 *máhtolaš
   4 *meroštallat
   4 *mealgadii
   4 *maōrigiella
   4 *láidestusaid
   4 *luohkkáduvvon
   4 *lohkamassii
   4 *liturgiijaid
   4 *lagamus
   4 *kymrigielalaš
   4 *kritihkalaččat
   4 *kriminálafullii
   4 *konfliktaráđiin
   4 *konfliktaráđi
   4 *katalánagiella
   4 *juohkehaččas
   4 *julevsámegielalaččat
   4 *iskkadeapmi
   4 *iskkadeamit
   4 *iralaš
   4 *heiveha
   4 *gárvánii
   4 *gáiddos
   4 *gullevašvuohta
   4 *guktuid
   4 *guhtege
   4 *gollevirgi
   4 *goappá
   4 *goabbáge
   4 *gihppaga
   4 *giellaja
   4 *giellafágalaččat
   4 *geavaheaddjiidjearahallamiid
   4 *geavadis
   4 *geatnegahttá
   4 *geatnegahttet
   4 *gaskavuođaid
   4 *galbema
   4 *galbbain
   4 *friddjema
   4 *friddjafuola
   4 *forskning
   4 *formála
   4 *fitnodagat
   4 *fierpmádaga
   4 *etáhtaide
   4 *etáhtaid
   4 *elektruvnnalaččat
   4 *eaŋgalasalbmát
   4 *ealáskahttinbarggus
   4 *ealáskahttinbarggu
   4 *ealáhus-
   4 *eaktuda
   4 *eaktodáhtolaš
   4 *dássidit
   4 *dárkilat
   4 *duogášdieđuid
   4 *duhát
   4 *dohkkehit
   4 *dohkkeha
   4 *doaimmahusaide
   4 *doaimmahusaid
   4 *diđolašvuohta
   4 *divaštallama
   4 *distribusjon
   4 *dikšojuvvot
   4 *dihtolágan
   4 *deavdda-
   4 *davvisámegielalaš
   4 *davviriikkalaš
   4 *dainge
   4 *bátnedearvvasvuođalaš
   4 *báskalašgiella
   4 *bálvalusas
   4 *bálvalusa
   4 *báljo
   4 *buohkanas
   4 *biibbalsearvái
   4 *biibbaljorgaleapmái
   4 *bearráigeahču
   4 *badjelaš
   4 *analysajoavku
   4 *analfabetismma
   4 *almmatge
   4 *alfabehttenprošeakta
   4 *alfabehtten
   4 *albmohahkii
   4 *addosiid
   4 *Wikipedia
   4 *Walesa
   4 *Viehka
   4 *Vejolaš
   4 *Ulbmilat
   4 *UNNas
   4 *Telefáksa
   4 *T
   4 *Stáhtalaš
   4 *Stuorrabritánnias
   4 *Stbïevnese
   4 *St
   4 *Snoasas
   4 *Skániid
   4 *SGL
   4 *SANKS
   4 *S
   4 *Romssas
   4 *Rekruhttenáŋgiruššan
   4 *Radio
   4 *Program
   4 *Prenten
   4 *Post
   4 *Porsáŋggu
   4 *Politihkalaš
   4 *Pedagogalaš
   4 *Ovttasvástádus
   4 *Olggosaddán
   4 *Oktasaš
   4 *Oidnosii
   4 *Oarjilsámegiela
   4 *Oahpaheaddjiid
   4 *OPPALAŠ
   4 *ONa
   4 *Njealjijagáš
   4 *Neahttabáiki
   4 *NAVa
   4 *M
   4 *Láidestusat
   4 *Loabága
   4 *Lillehámmera
   4 *Leif
   4 *Lasihit
   4 *Kriminálafuollaguovddáš
   4 *Kandidáhtta
   4 *Kandidáhtas
   4 *Jahkásaš
   4 *Izu
   4 *ISO/*IEC
   4 *IKT
   4 *Hárvves
   4 *Holm
   4 *Heivehit
   4 *Gáiddosoahpahusa
   4 *Guovttegielalaš
   4 *Guovdilis
   4 *Golut
   4 *Girkolaš
   4 *Gihpa
   4 *Geavaheaddjiid
   4 *Geatnegasvuohta
   4 *Galbeneiseváldi
   4 *GSI
   4 *FAD
   4 *Evenášši
   4 *Eurohparáđđi
   4 *Eurohparáđi
   4 *Engerdálii
   4 *Duoid
   4 *Digitála
   4 *Dielddanuori
   4 *Bachelorbargu
   4 *Arne
   3 *šáŋraid
   3 *ákkastallá
   3 *vuođđuduvvon
   3 *velá
   3 *utdanningen
   3 *sosiála
   3 *sivaid
   3 *servvoštallat
   3 *searvevuođa
   3 *seammalágan
   3 *sadjásaš
   3 *rámmaplána
   3 *ruhtadan
   3 *rollen
   3 *relevánta
   3 *proseassat
   3 *progrešuvnna
   3 *ovttasdoaibman
   3 *oppalašárvvoštallan
   3 *oktiiordnet
   3 *oktiiheivehit
   3 *mielddusin
   3 *miehtásámi
   3 *meroštallet
   3 *láidestit
   3 *ládje
   3 *lasihit
   3 *komponeremis
   3 *kandidáhtaid
   3 *hástaleaddji
   3 *hástala
   3 *hutkat
   3 *heivehuvvojit
   3 *govdodahkii
   3 *goappásge
   3 *giellaoahpalaš
   3 *geavatlaččat
   3 *geatnegahttit
   3 *gealbudahttet
   3 *gaskkustit
   3 *gaskkal
   3 *fuomášumiid
   3 *friddjet
   3 *fierpmádathuksema
   3 *estehtalaš
   3 *eanas
   3 *eaktudit
   3 *dievasmahttet
   3 *bohtosiid
   3 *bajásšaddanbirrasa
   3 *autonomiija
   3 *a
   3 *Váldodeaddu
   3 *Vuoruhuvvon
   3 *Systemáhtalaš
   3 *Læreren
   3 *I
   3 *Geatnegahtton
   3 *60-minuvtta
   2 gærhkoendepartemeente/*Nidarosa
   2 aalmogasse/*geavaheaddjiide
   2 Dorjesovveme/*heivehuvvot
   2 Bïevnesen/*láidestus
   2 @direktoráhtta/*Fylkesmánnit/jïlleskuvlh
   2 @\^*Iskkadeamit
   2 *šáŋrain
   2 *šláddjiivuođas
   2 *šláddjes
   2 *čáŋadan-kuvsji
   2 *čálihemiid
   2 *čájáhus
   2 *čáhttet
   2 *čáhjehii
   2 *čuoŋománu
   2 *čuovvumuššan
   2 *čuovvoluvvot
   2 *čuovvoluvvojit
   2 *čuovvolemiid
   2 *čuovvoleapmin
   2 *čuovvolančuoggát
   2 *čuovvola
   2 *čujuhuvvui
   2 *čovdosat
   2 *čohkkájeaddjiin
   2 *čoavddus
   2 *čoagganeapmái
   2 *čiekŋudit
   2 *čiekŋuda
   2 *čavgadat
   2 *čavga
   2 *čatnasit
   2 *Čuovvumuš
   2 *Čuovvolan
   2 *Čohkkájeaddjiin
   2 *áššáskuhttineiseváldái
   2 *áššeguovdilis
   2 *áŋgiruššamis
   2 *ávkašuvvet
   2 *átlasis
   2 *árvosaš
   2 *ángiruššanáigodahkii
   2 *álššaleappot
   2 *álššalaččat
   2 *álššaiduhttit
   2 *álgoálbmotpolitihkáriiguin
   2 *álgagii
   2 *álbmotrievttálaš
   2 *ál-
   2 *ájitkeahttá
   2 *áin
   2 *áimmahuššá
   2 *áigádit
   2 *áiggil
   2 *áigeguovdil
   2 *Östersund
   2 *Åre
   2 *Åarjelhsaemien
   2 *Älvdalen
   2 *Áššáigullevaš
   2 *ÁŊGIRUŠŠAN
   2 *Átlasis
   2 *Árvesjávri
   2 *Árjjatluovvi
   2 *Álggahuvvon
   2 *Álggahit
   2 *Áiluovtta
   2 *Áigeguovdilis
   2 *Áigeguovdil
   2 *wwwjeehkin*no
   2 *wwwgïele*org
   2 *wwwaate*no
   2 *www*unesco*no
   2 *www*ssb*no/*samer
   2 *www*skrivebua
   2 *www*samit*no
   2 *www*samediggi*se/4009
   2 *www*samediggi*no
   2 *www*risten*no
   2 *www*regjeringen*no
   2 *www*klara-*klok*no
   2 *www*infonuorra*no
   2 *web-*TV-saadtegh
   2 *walisalaš
   2 *walisalaččain
   2 *vásáhusvuđđosaš
   2 *vásáhusain
   2 *vásse
   2 *vánhe-
   2 *válmmašteamen
   2 *válmmastit
   2 *válmmasteamen
   2 *válljodatárvvoštallamat
   2 *válljodaga
   2 *válljejupmi
   2 *válljehahtti
   2 *váldosiidu
   2 *váldooasitFága
   2 *váldokanála
   2 *váldoguovlluin
   2 *váldoguovddáš
   2 *váldogihppagiid
   2 *váldogiellan
   2 *váldogiella
   2 *váldofáttát
   2 *váldodoaimmaid
   2 *váldodoaimmahusas
   2 *válddiid
   2 *válddahallama
   2 *váilivuođat
   2 *váilivuođa
   2 *váiddaáššiin
   2 *vuđul
   2 *vuđolaš
   2 *vurkejuvvon
   2 *vurkejuvvojit
   2 *vuođđuduvvot
   2 *vuođđudusa
   2 *vuođđudii
   2 *vuođđudettiin
   2 *vuođđoskuvlaoahppiid
   2 *vuostáiválddidettiin
   2 *vuosttasgieallan
   2 *vuosttasamanuensa
   2 *vuoruhuvvot
   2 *vuoruhusaid
   2 *vuoruhii
   2 *vuorjašumi
   2 *vuollegis
   2 *vuoittahallat
   2 *vuoittahallamin
   2 *vuoigat-
   2 *vuohta
   2 *vuogádatlaš
   2 *von
   2 *visogovalaš
   2 *virgádan
   2 *virggis
   2 *virggi
   2 *viidánivččii
   2 *viidánan
   2 *viggamušaide
   2 *videočuohpaldagaid
   2 *veršuvnnaid
   2 *vela
   2 *veajuiduhttin-
   2 *veahkkáivuođain
   2 *vahkkosaš
   2 *vahkkosaččat
   2 *upmesámegiella
   2 *upmesámegiela
   2 *unversála
   2 *unohas
   2 *unnitgiellaservodagain
   2 *unnimusgáibádusat
   2 *unge
   2 *ulbmálaš
   2 *ulbmálat
   2 *ulbmilsuorgin
   2 *ulbmilin
   2 *ulbmila
   2 *tvs
   2 *tv-saadtegidie
   2 *tv-saadtegh
   2 *tv-*kanálas
   2 *turoahpu
   2 *tro
   2 *tillit
   2 *testameanta
   2 *temáhtalaččat
   2 *teknihkalaččat
   2 *teater
   2 *tearpma
   2 *tearbmaráhkadanbarggus
   2 *tearbmajoavkku
   2 *sørsamisk
   2 *sátnegirjjid
   2 *sámgiela
   2 *sámepolitihkalaš
   2 *sámekultuvrralaš
   2 *sámegielgelbbolašvuohta
   2 *sámegielalažžan
   2 *sámegielalaččaid
   2 *sámegielalačča
   2 *sámegielaigui
   2 *systemáhtalaččat
   2 *synergibeavttu
   2 *symbolan
   2 *surggiidrasttideaddji
   2 *supmi
   2 *suomagillii
   2 *sullasaš
   2 *sulastahttá
   2 *stuorrut
   2 *stuorruduvvui
   2 *stuorru
   2 *stipendiáhtavirggiide
   2 *stipeandaortnega
   2 *statistikk
   2 *statistihkkii
   2 *statistihka9
   2 *spiehkastat
   2 *spesialiserejuvvon
   2 *sosiálaáššiin
   2 *sosiálaásahusain
   2 *sosiálaprošeavtta
   2 *sosiálabálvalusláhkii
   2 *sosiálabálvalusas
   2 *sosiálabargiid
   2 *sosiála-
   2 *sosialtjenester
   2 *sosialspørsmål
   2 *sorjájit
   2 *sodju
   2 *soahpahmuša
   2 *soabahanjoavku
   2 *skuvliiálgimii
   2 *skuvliibeassama
   2 *skrivebua
   2 *skolen
   2 *skoađastuvvon
   2 *skandinávialaš
   2 *siviila
   2 *siskkáldas
   2 *siskkobeallái
   2 *siskkobeallai
   2 *sisaváldimii
   2 *sirdáseami
   2 *sirdašuvvá
   2 *sirdašuvvan
   2 *sirdašumi
   2 *siida
   2 *sihkkarastojuvvo
   2 *sihkkarastimis
   2 *sierrapedagogalaš
   2 *servvoštallangiellan
   2 *servvoštallamis
   2 *servadahttindepartemeanta
   2 *seilot
   2 *searvvahit
   2 *searvamin
   2 *searvamiin
   2 *searvamii
   2 *searvadahttinministtar
   2 *searvadahttindepartementii
   2 *searvadahttindepartemeanta/Novrlaanten
   2 *searvadahttindepartemeanta/@direktoráhtta
   2 *seammamállet
   2 *seailumii
   2 *sajáiduvvan
   2 *sajádagas
   2 *rådgivningstjeneste
   2 *ráŋggáštusčađaheamis
   2 *ráŋggáštusáššiid
   2 *ráŋggáštussii
   2 *ráŋggástussii
   2 *rávvemušaid
   2 *rápmadoarjagiid
   2 *rámmaplánalávdegotti
   2 *rámmaid
   2 *rámat
   2 *rájáin
   2 *ráffe
   2 *rádjarasttideaddji
   2 *rádjaovttasbargui
   2 *ráddjejupmi
   2 *ráddjejumit
   2 *ráddjejumis
   2 *ruonáeatnanlaččat
   2 *ruhtaduvvot
   2 *ruhtadii
   2 *ruhtadedje
   2 *ruhtadeamis
   2 *riikkamiehtásaš
   2 *riggon
   2 *rievddaldeaddji
   2 *rievddalda
   2 *riektesihkkarvuhtiii
   2 *reálafága
   2 *resolušuvdna
   2 *relevánsa
   2 *rekvisišuvnna
   2 *rekruhttenáŋgiruššama
   2 *rekruhttenstrategiijas
   2 *rekruhttendoaibmabijuin
   2 *rekruhttendoaibmabidjui
   2 *rekruhttemis
   2 *rekruhttejuvvojit
   2 *rehabiliterenulbmil
   2 *regiuvdna-
   2 *registarat
   2 *registarastojuvvon
   2 *registarastit
   2 *regionála-
   2 *regiijen
   2 *rasttildeaddji
   2 *rasttiduvvojit
   2 *rasttidit
   2 *ras
   2 *rahčamušaid
   2 *radiosáddagiidda
   2 *radioi
   2 *radio-saadtegh
   2 *psykososiála
   2 *psykologiija
   2 *proševttas
   2 *prošeaktajođiheaddjiin
   2 *proseassas
   2 *proseassa
   2 *promillaprográmmii
   2 *prográmmabuvttadeaddjiid
   2 *progrešuvdna
   2 *profešuvdnaáddejumi
   2 *profešuvdnasurggiiguin
   2 *profešuvdnaoahpus
   2 *priváhtan
   2 *prentemii
   2 *prentejuvvonge
   2 *prentejuvvojit
   2 *preassadoarjagat
   2 *preassadoarjaga
   2 *preassadieđáhusaid
   2 *praktihkalaš
   2 *positiivvalaš
   2 *positiiva
   2 *poltitiijaovttadagain
   2 *politiijavirggálaččat
   2 *politiijavirggálačča
   2 *politihkárat
   2 *poliklinalaš
   2 *plásttain
   2 *persovnnalaš
   2 *pdfhámis
   2 *pasieantavuoigatvuođalága
   2 *ođđaáigásabbo
   2 *oáhpahusa
   2 *ovttaárvosašvuođa
   2 *ovttastuvvan
   2 *ovttasteami
   2 *ovttastallet
   2 *ovttastallangiellan
   2 *ovttastallangielas
   2 *ovttastallamis
   2 *ovttastallamiidda
   2 *ovttastaladettiin
   2 *ovttasdoaibmangiellan
   2 *ovttasdoaibman-
   2 *ovttasdoaibmama
   2 *ovttamielalašvuhtii
   2 *ovdánanit
   2 *ovdun
   2 *ovddimusas
   2 *ovddasástádus
   2 *ovddasvástidit
   2 *ovddasvástideaddjin
   2 *ovddasvástideaddji
   2 *ovddastit
   2 *ovddasteaddjiiguin
   2 *ovddalgihtii
   2 *ovdaságadoallin
   2 *ovdasiidui
   2 *ovdaprošeaktaohcama
   2 *ovdanboahtá
   2 *ovdalis
   2 *ovdagovvan
   2 *ovdabargui
   2 *ovd-
   2 *oskkolaš
   2 *ortnegis
   2 *ortnegii
   2 *orgainiserejuvvon
   2 *or
   2 *oppanassiige
   2 *operatiivavuogádagain
   2 *operatiiva
   2 *område
   2 *olámuddui
   2 *oluide
   2 *ollesbeaisaji
   2 *ollašuvvet
   2 *ollašuvvat
   2 *ollašupmái
   2 *ollašuhttojuvvvon
   2 *olgogova
   2 *olggobealláige
   2 *olggobeallái
   2 *oktovuođa
   2 *oktogiellan
   2 *oktilaš
   2 *oktiiheiveheami
   2 *oktiigullevažžan
   2 *oktiigullevašvuohta
   2 *oktasašoasit
   2 *oktasašfága
   2 *oktagassii
   2 *oktagassan
   2 *oktagasain
   2 *oktagasaide
   2 *oinnosmahttojuvvot
   2 *ohcanvejolaš
   2 *oasálažžii
   2 *oasálaččaid
   2 *oasálačča
   2 *oarjilsámit
   2 *oarjilsámiid
   2 *oarjilsámeguovllus
   2 *oarjilsámegielalaččat
   2 *oarjilsámegielain
   2 *oarjilsámegelalaš
   2 *oarjil-
   2 *oarje-eurohpalaš
   2 *oapposajiid
   2 *oahppiidlogu
   2 *oahpistit
   2 *oahphusfálaldaga
   2 *oahpaheddjioahpus
   2 *oahapahussuorggi
   2 *oadjomáksimiin
   2 *návččaiguin
   2 *náitima
   2 *nuortalččat/
   2 *nuortalašgillii
   2 *nuortalašgiella
   2 *nuortalaš/*goltálaš
   2 *nuortalaš
   2 *nuortalaččat/*golttálaččat
   2 *nubbingielas
   2 *nubbegiellafágas
   2 *nubbegiellafága
   2 *nubbegiellaeavttuidge
   2 *nubbegiella
   2 *normeremis
   2 *normeremiid
   2 *normeremat
   2 *normerema
   2 *nogai
   2 *no
   2 *njuovžilvuohta
   2 *njuovžilit
   2 *njuohkánahttán
   2 *njuohkána
   2 *njeadjan
   2 *neutrálat
   2 *nehttii
   2 *neathttasiidui
   2 *neahttavuđot
   2 *neahttavideosáddagiiguin
   2 *neahttasadji
   2 *neahttadiehtogirjji
   2 *neahttabálvalusat
   2 *neahttabáikái
   2 *neahttabáikkis
   2 *našuvnnalaš
   2 *nanusmuvvan
   2 *namm
   2 *namahuvvui
   2 *namahuvvon
   2 *namahuvvojit
   2 *namahuvvo
   2 *namahusat
   2 *namahit
   2 *namaha
   2 *nagadit
   2 *máŋggagielat
   2 *mávssolaš
   2 *máttás
   2 *márkosámit
   2 *mánáidgárd-
   2 *máinnasteapmi
   2 *máiddái
   2 *máhcaheapmi
   2 *máddin
   2 *musea
   2 *muosáhettiin
   2 *muhtumassii
   2 *movttiiduvvat
   2 *morfofonologalaš
   2 *molssaeavttot
   2 *moadde
   2 *mieldeváikkuhussii
   2 *meängillii
   2 *meängiela
   2 *metagiellange
   2 *meroštallá
   2 *meroštallojuvvon
   2 *mekánalaččat
   2 *meining
   2 *medvirkning
   2 *mearkkašahtti
   2 *mealgat
   2 *maōriálbmogis
   2 *maōrigiela
   2 *maōri-kultuvrem
   2 *maōri-gïelem
   2 *matge
   2 *masterprográmma
   2 *masteroahpuin
   2 *masteroahpu
   2 *master-*dássásaš
   2 *maorit
   2 *maorimánát
   2 *maorigiella
   2 *maoribearrašiin
   2 *maori-#gïeleldh
   2 *mannosaš
   2 *mainnalágiin
   2 *lážáldahkii
   2 *lážáldaga
   2 *lávdegiellan
   2 *láidestusávdnasiid
   2 *láidestus
   2 *láidestahkan
   2 *láidestagat
   2 *láidesta
   2 *lágáid
   2 *lágalaš
   2 *luođit
   2 *luohkkáduv-
   2 *lundui
   2 *luiket
   2 *logoin
   2 *lobálašvuođagoziheamis
   2 *liturgiijagiehtagirji
   2 *liturgiija
   2 *likeverd
   2 *liigemovttiidahttimii
   2 *liigegoluid
   2 *lihtodan
   2 *leappot
   2 *leairaoahppiid
   2 *lassánahtášii
   2 *lasihuvvui
   2 *lasihuvvojedje
   2 *lasiha
   2 *lain
   2 *lahttudit
   2 *lahkaásahus
   2 *lahkananvuohki
   2 *lahkalagaid
   2 *lagat
   2 *lagabut
   2 *kártehit
   2 *kymrigillii
   2 *kymrigielas
   2 *kymrigielalažžan
   2 *kymrigielalaččaid
   2 *kvalifiserejit
   2 *kultuvr-
   2 *kul-
   2 *kriteria
   2 *kristtalaš
   2 *kriminálafuollaguovddáš
   2 *kriminálafuolla
   2 *kontántadoarjaga
   2 *kontekstii
   2 *konteavsttain
   2 *konseapta
   2 *konfliktaráđiide
   2 *komposišuvnnas
   2 *kompensašuvdnan
   2 *komenten
   2 *komentejuvvui
   2 *komentejuvvon
   2 *komeanttaiguin
   2 *komeanttaidege
   2 *kombinašuvnna
   2 *kognitiiva
   2 *klinihkkii
   2 *klinihkka
   2 *klasihkalaš
   2 *keltalaš
   2 *kapihttalsis
   2 *kanálaid
   2 *jápma
   2 *jáhkehahtti
   2 *jábmejassii
   2 *jurisdikšuvdnaváttisvuohta
   2 *jure
   2 *juohkelágan
   2 *juohkehaš
   2 *juohkehačča
   2 *julevsámegielalaččaid
   2 *julevsámegieal
   2 *julesámegielas
   2 *juksamin
   2 *jođus
   2 *jođiheaddjiide
   2 *journalistavirggiin
   2 *journalistalaš
   2 *jorgaleaddjiid
   2 *joret
   2 *joregiidda
   2 *jorega
   2 *joba
   2 *joatkkaskuvl-
   2 *joargalahttit
   2 *jnv
   2 *jitnosit
   2 *jienastanagi
   2 *iskkademiid
   2 *iskkadeami
   2 *iskkadallamat
   2 *iskat
   2 *irlándalaš
   2 *iralaččain
   2 *iralaččaid
   2 *iragállálaš
   2 *iragillii
   2 *iragielalaš
   2 *ipmirdahtti
   2 *ipmilbávalusteavsttaid
   2 *inuihttagiela
   2 *interaktiiva
   2 *informasjonssystem
   2 *indikáhtorat
   2 *illásteami
   2 *iešáddejupmi
   2 *iešvuođain
   2 *iešvuohtan
   2 *iešstivrema
   2 *iešluohttámuša
   2 *iešheanalaččat
   2 *iešdovddu
   2 *hárvásat
   2 *hárvves
   2 *hárve
   2 *hárjáneapmi
   2 *hálttis
   2 *hálddahuslaš
   2 *hutki
   2 *http//*www*hifm*no/*drommejobben
   2 *http//*www*helsinki*fi/~*tasalmin/*europe_*report*html
   2 *hivvomediat
   2 *historjjálaš
   2 *historjjálaččat
   2 *helseog
   2 *helse-
   2 *heivehallamis
   2 *heivehallama
   2 *hedjoneapmi
   2 *heađuštusaid
   2 *heađuštit
   2 *hearkkes
   2 *heapmi
   2 *hawaii-gïele
   2 *gáržžida
   2 *gárrenmirkkuide
   2 *gárihansuodjalusas
   2 *gárihanfuolla
   2 *gárihandivššus
   2 *gárdumiin
   2 *gánnáhahttin
   2 *gáiddosoahpaheami
   2 *gáiddosoahpahanneavvuiguin
   2 *gáibádus
   2 *gáhttejupmái
   2 *guđesge
   2 *guovttegielalašvuohta
   2 *guovllulaš
   2 *guovllud
   2 *guovdilat
   2 *guovdil
   2 *guottuid
   2 *gullevažžan
   2 *gulaskuddá
   2 *gulaskuddandadjamuš
   2 *gulaskuddancealkámušaid
   2 *gulahuvvot
   2 *gulahit
   2 *guktot
   2 *guktii
   2 *guhtet
   2 *guhkodagas
   2 *guhkkelii
   2 *guhkebuš
   2 *goziha
   2 *govdodat
   2 *goluid
   2 *golttát
   2 *golttágiella
   2 *golmmaolbmo
   2 *golbmasis
   2 *goit
   2 *gohččosa
   2 *goappašat
   2 *gittauvssaid
   2 *gis
   2 *girkostallanárbevieruide
   2 *girkostallan
   2 *gihppagiin
   2 *gihppagat
   2 *gihpa
   2 *gieskadaš
   2 *giellapedagogalaš
   2 *giellanjuoggadusaid
   2 *giellageavaheaddjiiguin
   2 *gielladieđalaš
   2 *gielladieđalaččat
   2 *gielaid3
   2 *giddagasvirggálaččaid
   2 *giddagasvirggálačča
   2 *gednojuvvo
   2 *geavaheaddjiidjearahallama
   2 *geatnegavuođaid
   2 *geatnegasvuođat
   2 *geatnegasvuođaiguin
   2 *geatnegasvuođaideamet
   2 *geatnegasvuhtii
   2 *geatnegas
   2 *geallagiela
   2 *gealbudahttá
   2 *gealbudahttit
   2 *geahčadeaddjiid
   2 *geahppudit
   2 *gaskkusteapmi
   2 *gaskaleamos
   2 *gaskaboddosaš
   2 *galbá
   2 *galbenváldi
   2 *galbengoluid
   2 *galbeneiseváldái
   2 *galbejuvvot
   2 *galbejuvvo
   2 *galbbaiguin
   2 *galbbaide
   2 *galbbaid
   2 *fápmudit
   2 *fámuiduvvá
   2 *fámuiduvve
   2 *fámuiduvvan
   2 *fámuiduhttit
   2 *fámuiduhttimis
   2 *fáluid
   2 *fállamassii
   2 *fágalaččat
   2 *fágadidákttalaš
   2 *fáddádat
   2 *fysioterapiijabálvalusas
   2 *fuomášumi
   2 *fuolahuvvot
   2 *fuolahusdepartemeanta/#Vervies
   2 *friddjenmearrádusat
   2 *friddjafuollakontuvrras
   2 *friddjafuollakontuvrraid
   2 *friddjafuolas
   2 *friddjadáhtus
   2 *friddja
   2 *formulára
   2 *formaliseret
   2 *fonetihka
   2 *fitnolaš
   2 *fierpmádatčoahkkimiid
   2 *fierpmádagain
   2 *festiválat
   2 *farga
   2 *etáhtatge
   2 *etáhtain6
   2 *etáhtain
   2 *entreprenørskap
   2 *eisege
   2 *eaŋgalasgillii
   2 *eaŋgalasgiela
   2 *eavttuhit
   2 *eatnašat
   2 *easkkavirgáduvvon
   2 *earáhuvvet
   2 *ealáskahttojuvvot
   2 *ealáskahttinlihkadusa
   2 *ealáskahttindoaibmabiju
   2 *ealáskahttinbargguid
   2 *ealáskahttimin
   2 *ealáskahttimiin
   2 *ealáskahttima
   2 *ealáskahttet
   2 *ealáhusaide
   2 *ealáhusa-
   2 *ealáhus
   2 *eaktodáhtolaččaid
   2 *eahpeformála
   2 *eahpedárkilat
   2 *eahkedismállásiid
   2 *dávvisámegiela
   2 *dávgasut
   2 *dássážii
   2 *dáruiduhttinpolitihkka
   2 *dáruiduhttinpolithkka
   2 *dáruiduhttindeattu
   2 *dárogielfágas
   2 *dárogielfágain
   2 *dárogiel-saemiengïelen
   2 *dáro-sámegielalaš
   2 *dárkilis
   2 *dárki-
   2 *dánskkagillii
   2 *dálážii
   2 *dáláš
   2 *dáiddársoahpamušas
   2 *dáiddárorganisašuvnnain
   2 *dáiddáriid
   2 *dáhpáhusainhan
   2 *dábálášoahpaheaddjeoahpu
   2 *dutkanaktiivvalaš
   2 *dutkamaiid
   2 *duppalastojuvvui
   2 *duopmáriin
   2 *duoidda
   2 *duogážis
   2 *duogážiin
   2 *duogážat
   2 *duogášge
   2 *duhtameahttunvuođa
   2 *duhtameahttumat
   2 *duhtada
   2 *duhkoraddamiin
   2 *dovddaheamit
   2 *dovddaha
   2 *dohkálašvuođa
   2 *dohkkehettiinis
   2 *doaŋggit
   2 *doaimmahuvvot
   2 *doaibmanáigodat
   2 *doaibmamuščállosiin
   2 *doaibmamuš
   2 *divššáriid
   2 *divššohasdikšu
   2 *divššohasat
   2 *divššohasaiguin
   2 *divššohasaide
   2 *divššohasaid/*lagamus
   2 *divaštallamis
   2 *divaštaladettiinis
   2 *dit
   2 *diiddat
   2 *dihtorprográmmaid
   2 *dihtorlingvistihkkii
   2 *dihtoriin
   2 *dihtora
   2 *dieđaárbevieru
   2 *dieđagiellan
   2 *dievasgielalažžan
   2 *diehttevassii
   2 *diehtojuohkinpláhkáhat
   2 *diehtagiid
   2 *didákttalaš
   2 *det
   2 *den
   2 *deattuhuvvot
   2 *deattastit
   2 *deattasta
   2 *deastta
   2 *dearvvasvuođaregiuvnna
   2 *dearvvasvuođalaš
   2 *dearvvasvuođaja
   2 *deamis
   2 *deaivvahit
   2 *deaivilit
   2 *dađe
   2 *davábealde
   2 *davvisámegielalaččat
   2 *dasvástádus
   2 *darvánan
   2 *dakkáraččaid
   2 *dakko
   2 *dakkaviđe
   2 *dahkojietnaprográmma
   2 *dahkojierpmi
   2 *dagaha
   2 *dadjamuššii
   2 *cealkámušaid
   2 *caggama
   2 *bálvalustiippaid
   2 *bálvalussii
   2 *bálvalusfálaldagat
   2 *bálvalusfálaldaga
   2 *bálvalusfáladagaiguin
   2 *bálvalusdoaimmaide
   2 *bálvalusain
   2 *bálkkašanvuogádagat
   2 *bálddalas
   2 *bygger
   2 *buresloaktima
   2 *buresheivehuvvon
   2 *buresdoaibmi
   2 *buotsámi
   2 *buorimus
   2 *buoril
   2 *buohtalas
   2 *buohcuvuođa
   2 *buohccájit
   2 *buhtte
   2 *broer
   2 *bođđet
   2 *bođđemii
   2 *bođolažžan
   2 *boađusjuksan
   2 *boađusin
   2 *boastto
   2 *boaittobeallin
   2 *bmotlohkamis
   2 *blogget
   2 *biđgolas
   2 *bisttii
   2 *bistit
   2 *bistet
   2 *bissánkeahttá
   2 *bissovašvuođa
   2 *bissovašvuhtii
   2 *bismagoddi
   2 *biibbalteavsttat
   2 *biibbalteavsttaid
   2 *biibbalsearvi
   2 *biibbal
   2 *bihtánsámit
   2 *bihtánsámiiguin
   2 *bihtánsámesearvi
   2 *bihtánsámegiella
   2 *bihtánsámegielalaš
   2 *ben
   2 *befolkning
   2 *beavttálmahttet
   2 *bearráigeahčus
   2 *beannot
   2 *beaktilis
   2 *bastit
   2 *barn
   2 *barguimáhcahanbálvalusain
   2 *bargamušat
   2 *bajásšaddi
   2 *bajásšaddet
   2 *bajásšaddanguovddážii
   2 *bajásšaddandilálašvuođaid
   2 *bajásšaddandillái
   2 *bajásšaddan
   2 *bajásgeassima
   2 *baicce
   2 *bagadusa
   2 *bachelorbargui
   2 *bachelorbarggu
   2 *avis
   2 *aviiissaide
   2 *automáhtalaš
   2 *asttuin
   2 *astosuorggi
   2 *astojoregat
   2 *astofálaldagaiguin
   2 *astoberoštumiid
   2 *aspiránttain
   2 *aspirántta
   2 *artisttat
   2 *arenain
   2 *anárašgillii
   2 *anglo-*amerihkálaš
   2 *and
   2 *alternašuvnnain
   2 *almmuhusteavsttas
   2 *almmuhussan
   2 *almmuhusainis
   2 *almmuhusaide
   2 *allaárvosaš
   2 *alfabehttenprošeavtta
   2 *albmohagas
   2 *albmanit
   2 *aktiivalaččat
   2 *akkrediterejuvvon
   2 *aivvestassii
   2 *ainovdánahttot
   2 *aiddostit
   2 *aiddofal
   2 *ahkásaš
   2 *Zealándda
   2 *YOUTUBE
   2 *Wiktionary
   2 *Vásáhusaid
   2 *Váldohástalus
   2 *VÁSÁHUSAT
   2 *Vuođđuduvvon
   2 *Vuođđudusa
   2 *Vuođđudus
   2 *Vuoruhuvvot
   2 *Vualčir
   2 *Virggit
   2 *Viggamuš
   2 *Veterinearaallaskuvllas
   2 *VUOĐĐUDAN
   2 *Upmi
   2 *Unnitgielaidlihtu
   2 *Unjárggas
   2 *Unjárgga
   2 *Ume
   2 *Ulbmilin
   2 *ULBMIL
   2 *Tove
   2 *Todal
   2 *Telemárkku
   2 *Teknihkalaččat
   2 *Teatere/*Sydsamisk
   2 *Tearpmat
   2 *TV-*kanála
   2 *TV-
   2 *Sørsamisk
   2 *Sávahahtti
   2 *Sámeálbmotfoandda1
   2 *Sámepolitihkalaš
   2 *Sámepolithkka
   2 *Sámelaga
   2 *Sámegielmáhttu
   2 *Sámegielalaš/*dárogielalaš
   2 *Sámediggá
   2 *Sámdiggi
   2 *Sálttus
   2 *Sálttu
   2 *Sáltovuonas
   2 *Sáltoduoddaris
   2 *Sáltoduoddara
   2 *SÁMEGIELALAŠ
   2 *Syntehtalaš
   2 *Sváhkena
   2 *Svaahken
   2 *Suorsa
   2 *Suomagiela
   2 *Stuorrabritánniai
   2 *Strömsund
   2 *Storuman
   2 *Stipeandda
   2 *Statistihkas
   2 *Standárdenráđđi
   2 *Standard
   2 *St*dieđ
   2 *Språk
   2 *Spesialiserema
   2 *Soria
   2 *Skániin
   2 *Skotlánddas
   2 *Skandinávias
   2 *Sivva
   2 *Sirpmá
   2 *Siri
   2 *Siida
   2 *Sešuvnna
   2 *Samisk
   2 *Salmer
   2 *Saami
   2 *SVÁHKENA
   2 *STUDERENGELBBOLAŠVUHTII
   2 *STH-*foanda
   2 *SIIDA
   2 *SIERRANAHTTI
   2 *SEG
   2 *SANKSain
   2 *Rámmaplána
   2 *Ruoŧŧilaš
   2 *Romsii
   2 *Risten*no
   2 *Ringeriikka
   2 *Riikkalaš
   2 *Retten
   2 *Rekruttere
   2 *Rekruhttendoaibmabidju
   2 *Regionála
   2 *Regional
   2 *Referánsadieđut
   2 *Raportemis
   2 *ROMSSA
   2 *RKK
   2 *RIIKKAIN10
   2 *Proseassa
   2 *Project
   2 *Primusii
   2 *Preassadoarjja
   2 *Porsáŋggus
   2 *Plassje
   2 *Pite
   2 *Ovttasráđiid
   2 *Ovttasdoaibmanođastus
   2 *Ovddimusas
   2 *Ovddasvásrádus
   2 *Ovdasátni
   2 *Ovdalis
   2 *Otnáš
   2 *Ortnega
   2 *Oppgaveregisteret
   2 *Oppa
   2 *Oktilaččat
   2 *Oktagaslaš
   2 *Ohcejoga
   2 *Ofuohta
   2 *Ofoten
   2 *Od*prp
   2 *Oarjilsámit
   2 *Oarjilsámegiella
   2 *Oarjilsámegielas
   2 *Oarjilsámegielalaš
   2 *Oarjilsámegelalaš
   2 *OarjeFinnmárkkus
   2 *Oarje-Eurohpasge
   2 *OVTTASRÁĐIID
   2 *OVDASÁTNI
   2 *OTNÁŠ
   2 *ON-bæjhkoehtimmiem
   2 *ON-bæjhkoehtimmie
   2 *Nystad
   2 *Nuppádassii
   2 *Nuortalašgiella/*golttágiella
   2 *Nuortalašgiella/
   2 *Nuortalašgielas/*golttágielas
   2 *Nuortalašgiela/*golttágiela
   2 *Nuortaja
   2 *Norgesglasset
   2 *Norge
   2 *Nord-*Salten
   2 *Nord
   2 *Njávdámis
   2 *Nils
   2 *Nastedh
   2 *NUORTALAŠ
   2 *NRK3-saadtegidie
   2 *NRK3
   2 *NRK1
   2 *NAŠUNÁLA
   2 *NAVii
   2 *NAVbargiid
   2 *NAV-kontovride
   2 *NAV-kontovri
   2 *NAV
   2 *Mål
   2 *Mátta-*Várjjaga
   2 *Mánáidáitariid
   2 *Mánáidgárd-
   2 *Máhttodepartemanta
   2 *MÁRKOMÁNÁK
   2 *Moria-bæjhkoehtimmie
   2 *Mittådalenii
   2 *Minority
   2 *Maōritge
   2 *Maōri-gïele
   2 *Masteroahpuin
   2 *Mangfold
   2 *MOATTI
   2 *Lávvu
   2 *Láidestusgihpa
   2 *Láidestus
   2 *Luvlieluspái
   2 *Lohkmii
   2 *Likšu
   2 *Lars
   2 *Languages
   2 *LK06-*S
   2 *LK06
   2 *Kártenbargguid
   2 *Kárten
   2 *Kymrigiella
   2 *Kymrigiela
   2 *Kvalitet
   2 *Kriminálafuolas
   2 *Konfliktaráđi
   2 *Klok
   2 *Klara
   2 *Kampánnja
   2 *KRUSain
   2 *Justiisapartemeanta
   2 *Jon
   2 *Johnsen
   2 *Jo1*as
   2 *Jiellevárri
   2 *Iragiella
   2 *Infonuorra
   2 *ITii
   2 *INDIKÁHTORAT
   2 *ILO-latjkoem
   2 *ILO-konvensjovne
   2 *IKTa
   2 *IKT-gaskesinie
   2 *IKT-evtiedimmie
   2 *IKT-aatine
   2 *IKT-
   2 *Härjedalen
   2 *Hálddahuslaš
   2 *Hordalándda
   2 *Helse
   2 *Hawaii-sååline
   2 *Hawaii-sååli
   2 *Hawaii-#tjuedtjielidh
   2 *Hamlet
   2 *HUMBOLDT-UNIVERSITEETEN
   2 *Gáibádus
   2 *Guđege
   2 *Guovttegielalašvuođas
   2 *Guovttegielalašvuohta
   2 *Gulaskuddannotáhtta
   2 *Guktuid
   2 *Guhtege
   2 *Grunnskolens
   2 *Goappaš
   2 *Giellafágalaš
   2 *Gielem
   2 *Gielddalaš
   2 *Geavaheaddjiin
   2 *Geavaheaddjiidjearahallan
   2 *Geavaheaddjiidjearahallamiid
   2 *Geavadis
   2 *Gaup
   2 *GUHKESÁIGÁSAŠ
   2 *GIELLATEKNO
   2 *GG
   2 *GASKABODDOSAŠ
   2 *FÁPMUIBOAHTIN
   2 *Fuoskku
   2 *Friddjen
   2 *Friddjafoandda
   2 *Franco-ståvroem
   2 *Foandda
   2 *Foanda
   2 *Finmárku
   2 *Fidnofágalaš
   2 *Facebook
   2 *FRIDDJAFOANDAORTNET
   2 *FIDNOFÁGALAŠ ÖÖHPEHTIMMIEPROGRAMMINE
   2 *European
   2 *Eurohpalaš
   2 *Eurohpa
   2 *Espánnjas
   2 *Eretfárremat
   2 *Eaŋgalánddas
   2 *Eatnašat
   2 *Ealáskahttin
   2 *Eahpesihkkaris
   2 *Eahpefitnolaš
   2 *EAKTUDA
   2 *Dánnego
   2 *Duon
   2 *Duoddará
   2 *Drømmejobben/*Gollevirgi
   2 *Documentation
   2 *Doaimmahusas
   2 *Doaibambidju
   2 *DjO
   2 *Diđolašvuohta
   2 *Divššohasaide
   2 *Divttasvuotna
   2 *Dihtorlingvistihkas
   2 *Dieđateoriija
   2 *Den
   2 *Deattuhuvvon
   2 *Deattuhuvvo
   2 *Deattuhettiin
   2 *Dearvvavuođafitnodagat
   2 *Dearvvasvuođarievttálaš
   2 *Dearvvasvođabargiid
   2 *Deardnái
   2 *Davvisámegielalaš
   2 *DavviTrøndelágas
   2 *Daidda
   2 *DVD-jielieguvviem
   2 *DIVTTASVUONA
   2 *DAVVI-EUROHPA
   2 *Charter
   2 *Bálága
   2 *Báikkálaš
   2 *Báidaris
   2 *Buohkanassii
   2 *Bull
   2 *Brønnøysundregistariidda
   2 *Bođolaš
   2 *Bohtosiid
   2 *Bodåddjå
   2 *Boarraseappoš
   2 *Bihtánsámit
   2 *Bihtánsámegiela
   2 *Berg
   2 *Beholde
   2 *Bajilgovva
   2 *BUP
   2 *BERLIINNAS
   2 *B
   2 *Askeladdenii
   2 *Aotearoa
   2 *Andreassen
   2 *Altinn
   2 *Akershusas
   2 *Aajege
   2 *1960ja
   1 –*metodat
   1 §*i
   1 maahtaldahkeulmieh*Bajilgovva
   1 daastine*
   1 @\^*Jo1-*Jo3
   1 8-*
   1 *čuovvolii
   1 *čavgadit
   1 *Čujuhuvvo
   1 *Čujuhit
   1 *ámmátoktavuođain
   1 *ámmáha
   1 *ákkastallamat
   1 *ákka
   1 *ággan
   1 *Åge
   1 *Ánde
   1 *Álggahankollokviat
   1 *Ákkastallan
   1 *Ákkastallama
   1 *váldočuoggát
   1 *váldogielaid
   1 *válddahusain
   1 *válddaha
   1 *vuđoleappot
   1 *vuođđoskuvlaoahpaheaddjeohpu
   1 *vuođuštussan
   1 *vuođusteapmi
   1 *vuosttašdahje
   1 *vuoruheapmi
   1 *vuolggahuvvon
   1 *vuolggahii
   1 *višuvnnat
   1 *virgáibidjamis
   1 *virgáduvvo
   1 *virgádeapmái
   1 *virggiid
   1 *universitehtapolitihkalaš
   1 *ulbmilparagráfas
   1 *sátnádit
   1 *sámegielarenat
   1 *suokkardit
   1 *stuoramus
   1 *studeret
   1 *studerenráhkanahtti
   1 *studeren-maahtaldahkese
   1 *struktureret
   1 *statistihkain
   1 *spiehkasteamit
   1 *soitet
   1 *skuvlenásahusaid
   1 *sirrejit
   1 *sihkkarastima
   1 *seavagiella
   1 *rámmaplánii
   1 *rámmaplánalávdegottiin
   1 *ráhkadusa
   1 *ráhkadišgđii
   1 *resoneren
   1 *resonerema
   1 *repertoara
   1 *rekrutterenvirggiid
   1 *reflekteredit
   1 *referánsarámmat
   1 *reella
   1 *proseassan
   1 *proseassaid
   1 *profileremii
   1 *profilere
   1 *prinsihpa
   1 *populearadieđalaš
   1 *paragráfat
   1 *očmejnie
   1 *ovttastumiin
   1 *ovddasteaddjesadji
   1 *ovddabealde
   1 *oppalaščuvgejumis
   1 *oppalaččat
   1 *olggobeali
   1 *oktiigullevašvuođas
   1 *oktasašvuođat
   1 *oaččuheapmái
   1 *oallugat
   1 *oainnusmahttit
   1 *nubbingiellanfága
   1 *máŋggafágalaš
   1 *máŋggabealát
   1 *mávssolašvuođa
   1 *musea/@musea
   1 *muosáhussii
   1 *muosáhusaiguin
   1 *muosáhusaide
   1 *muosáhusaid
   1 *muosáheamis
   1 *molsašuddi
   1 *mihtilmas
   1 *mielddusoassi
   1 *metodat
   1 *meroštallamiid
   1 *maŋemuččat
   1 *ložžet
   1 *lohkanbajioahpu
   1 *logihkalaš
   1 *kveanagiella
   1 *kvalifiserenrámmaid
   1 *kultuvradieđu
   1 *kreatiivvalaččat
   1 *konstruktiiva
   1 *kandidáhttá
   1 *jotkkolaš
   1 *internašunaliseren
   1 *integreret
   1 *iešmearrideapmi
   1 *iešguđetládje
   1 *hálidit
   1 *hálida
   1 *hutkás
   1 *hutkkálaččat
   1 *httit
   1 *hovdengotti
   1 *gávnnahuvvui
   1 *gáržžiduvvon
   1 *gáržžideami
   1 *gárven
   1 *gáibádussan
   1 *gáibádusa
   1 *guovttegielagin
   1 *guovdásj
   1 *guoskevaš
   1 *gulaskuddannotáhtii
   1 *gráfalaš
   1 *govdodagain
   1 *girjás
   1 *gierdilvuođain
   1 *giellagelbbolašvuođainvuođđun
   1 *geavadiid
   1 *fuolkevuođagullevašvuohta
   1 *friddjenmearrádusaid
   1 *friddjejuvvojit
   1 *friddjejuvvo
   1 *friddjaoastinortnegiid
   1 *fakultehtaid
   1 *earáhuhttojuvvon
   1 *earaládje
   1 *e
   1 *dáđistaga
   1 *dávggasin
   1 *dássálagaid
   1 *dárkilut
   1 *dádjadit
   1 *dovddiidussii
   1 *dovdaga
   1 *dohkkehii
   1 *doalahuvvo
   1 *doalahit
   1 *doaimmaheapmi
   1 *diđoštit
   1 *dieđalaš
   1 *dievasmahttá
   1 *dekodengálggaid
   1 *davviriikkalaš-*ruošša
   1 *d
   1 *c
   1 *buoremuslági
   1 *boahttevuođas
   1 *birgejupmi
   1 *bie1800
   1 *bibliografiija
   1 *beaktilit
   1 *baicca
   1 *bagadallojuvvon
   1 *arvvosmahttit
   1 *arenan
   1 *almma
   1 *albmanahttit
   1 *akademalaš
   1 *ainovdánahttojit
   1 *Višuvnnat
   1 *Viidáset
   1 *Suokkardit
   1 *Stuoradiggedieđahusas
   1 *Stuoradiggediedáhus
   1 *Studeren-båårestæjjan
   1 *Stipeanda
   1 *Somby
   1 *Sivvan
   1 *Sisaváldinláhkaásahusa
   1 *Sirdašuvvan
   1 *STUDERENRÁHKKANAHTTI
   1 *Rávná
   1 *Rámmaplánalávdegoddi
   1 *RMD-gærjagåetien
   1 *Pedersen
   1 *Ođastusa
   1 *Oallugat
   1 *O97S
   1 *Má
   1 *Mielddusoassái
   1 *Mielddusoassi
   1 *Merete
   1 *Med-*fak
   1 *Master-programmem
   1 *Kramvig
   1 *Kompetanseforskriften
   1 *Jo2*is
   1 *Jo
   1 *ILO
   1 *Hálidan
   1 *Historjjálaš
   1 *Gáibádussan
   1 *Fásta
   1 *Fágalaš
   1 *Fakultehtaid
   1 *FRIDDJENMEARRÁDUSAT
   1 *FIDNOFÁGALAŠ
   1 *Dávgasis
   1 *DGT
   1 *Britt
   1 *Berit
   1 *Bajásšaddanjođiheaddji
   1 *Bahcelorbargu
   1 *Almmatge
   1 *1čálalaš
   1 **Fidnofágalaš
   1 *
